services:
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - tempo
      - prometheus
    networks:
      - observability

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/config.yml -config.expand-env=true
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: -config.file=/etc/tempo/tempo-config.yml
    volumes:
      - ./tempo-config.yml:/etc/tempo/tempo-config.yml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    container_name: otel-collector
    command: [ "--config", "/etc/otel/config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel/config.yml
    ports:
      - "4317:4317" # gRPC (para o SDK)
      - "4318:4318" # HTTP (para debug)
    depends_on:
      - tempo
      - loki
      - prometheus
    networks:
      - observability

volumes:
  grafana-data:
  loki-data:
  tempo-data:
  prometheus-data:


networks:
  observability:
    driver: bridge
