server:
  http_listen_port: 3200
  log_level: info

memberlist:
  join_members: []

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

compactor:
  compaction:
    block_retention: 720h
