receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

extensions:
  health_check: {}

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure_skip_verify: true
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
    
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp/v1/logs"
    tls:
      insecure: true
  debug:
    verbosity: detailed 

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki]