name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SSH_HOST }}
          username: ${{ secrets.STAGE_SSH_USER }}
          key: ${{ secrets.STAGE_SSH_KEY }}
          script: ~/deploy-scripts/trouw-ms-audit-service.sh